---
- name: "Apply common k8s node prerequisites"
  ansible.builtin.include_tasks: "common.yml"

- name: "Initialize control plane"
  when: "inventory_hostname is match('cp(-[0-9])?')"
  ansible.builtin.include_tasks: "control_plane.yml"

- name: "Join as worker node"
  when:
    - "inventory_hostname is not match('cp(-[0-9])?')"
    - "groups['all'] | select('match', 'cp(-[0-9])?') | list | length > 0"
  ansible.builtin.include_tasks: "worker.yml"
